upstream frontend {
    server frontend:3000;
}

upstream strapi {
    server strapi:1337;
}

server {
    listen 80;

    location / {
        proxy_pass http://frontend;
    }

    location /strapi/ {
        proxy_pass http://strapi/;
    }
}